import Head from 'next/head'
import Image from 'next/image'
import {useState, useEffect} from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
    const [numbersList, setNumbersList] = useState([])

    useEffect(() => {
        fetch('http://localhost:3000/api/hello')
            .then(res => res.json())
            .then(data => {
                setNumbersList( data.name );
            })

    }, [])

    if (!numbersList) return <p>Empty, no data</p>

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <ul>
                    {numbersList.map(number => {
                        // eslint-disable-next-line react/jsx-key
                        return <li>{number}</li>
                    })}
                </ul>
            </main>

            <footer className={styles.footer}>
                <button>
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </button>
            </footer>
        </div>
    )
}
